"""new fields in user model

Revision ID: 706847f5f5bc
Revises: b6f335c3d693
Create Date: 2018-06-04 14:46:40.463453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706847f5f5bc'
down_revision = 'b6f335c3d693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
